name: PR Prioritization R5 Check
on:
  schedule:
#    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
    - cron: '0 */1 * * *' # Runs every 1 hours

jobs:
  update_project_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check and Assign R5 Priority to PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/assign-r5-priority.js')
            await script({github})