name: PR Prioritization Update
on:
  schedule:
    # - cron: '0 */6 * * 1-5'  # Runs every 6 hours during weekdays
    - cron: '0 */1 * * *' # Runs every 1 hours
  workflow_dispatch:        # Manual trigger

jobs:
  update_project_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check and assign R2 Priority to PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/assign-r2-priority.js')
            await script({github})

      - name: Update Needs Attention Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/update-attention-status.js')
            await script({github})
