name: Test Failing Check
on:
  workflow_dispatch:
    inputs:
      should_fail:
        description: 'Should this check fail?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  failing_check:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Check
        run: |
          if [ "${{ github.event.inputs.should_fail || 'true' }}" = "true" ]; then
            echo "Making check fail for testing"
            exit 1
          else
            echo "Making check pass for testing"
            exit 0
          fi